/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_bitfire_gfxtablet_NetworkClient */

#ifndef _Included_at_bitfire_gfxtablet_NetworkClient
#define _Included_at_bitfire_gfxtablet_NetworkClient
#ifdef __cplusplus
extern "C" {
#endif
#undef at_bitfire_gfxtablet_NetworkClient_GFXTABLET_PORT
#define at_bitfire_gfxtablet_NetworkClient_GFXTABLET_PORT 40118L
#undef at_bitfire_gfxtablet_NetworkClient_TYPE_MOTION
#define at_bitfire_gfxtablet_NetworkClient_TYPE_MOTION 0L
#undef at_bitfire_gfxtablet_NetworkClient_TYPE_BUTTON
#define at_bitfire_gfxtablet_NetworkClient_TYPE_BUTTON 1L
/*
 * Class:     at_bitfire_gfxtablet_NetworkClient
 * Method:    create
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_at_bitfire_gfxtablet_NetworkClient_create
  (JNIEnv *, jobject);

/*
 * Class:     at_bitfire_gfxtablet_NetworkClient
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_bitfire_gfxtablet_NetworkClient_destroy
  (JNIEnv *, jobject);

/*
 * Class:     at_bitfire_gfxtablet_NetworkClient
 * Method:    setNetworkConfig
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_at_bitfire_gfxtablet_NetworkClient_setNetworkConfig
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_bitfire_gfxtablet_NetworkClient
 * Method:    sendEvent
 * Signature: (BFFFIZ)V
 */
JNIEXPORT void JNICALL Java_at_bitfire_gfxtablet_NetworkClient_sendEvent__BFFFIZ
  (JNIEnv *, jobject, jbyte, jfloat, jfloat, jfloat, jint, jboolean);

/*
 * Class:     at_bitfire_gfxtablet_NetworkClient
 * Method:    sendEvent
 * Signature: (BFFF)V
 */
JNIEXPORT void JNICALL Java_at_bitfire_gfxtablet_NetworkClient_sendEvent__BFFF
  (JNIEnv *, jobject, jbyte, jfloat, jfloat, jfloat);

/*
 * Class:     at_bitfire_gfxtablet_NetworkClient
 * Method:    setAreaSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_at_bitfire_gfxtablet_NetworkClient_setAreaSize
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
